/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EgtpCard: typeof import('./src/components/egtp-card.vue')['default']
    EgtpSwiper: typeof import('./src/components/egtp-swiper.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutCell: typeof import('nutui-uniapp/components/cell/cell.vue')['default']
    NutCellGroup: typeof import('nutui-uniapp/components/cellgroup/cellgroup.vue')['default']
    NutCheckbox: typeof import('nutui-uniapp/components/checkbox/checkbox.vue')['default']
    NutDivider: typeof import('nutui-uniapp/components/divider/divider.vue')['default']
    NutForm: typeof import('nutui-uniapp/components/form/form.vue')['default']
    NutFormItem: typeof import('nutui-uniapp/components/formitem/formitem.vue')['default']
    NutGrid: typeof import('nutui-uniapp/components/grid/grid.vue')['default']
    NutGridItem: typeof import('nutui-uniapp/components/griditem/griditem.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutInput: typeof import('nutui-uniapp/components/input/input.vue')['default']
    NutMenu: typeof import('nutui-uniapp/components/menu/menu.vue')['default']
    NutMenuItem: typeof import('nutui-uniapp/components/menuitem/menuitem.vue')['default']
    NutTabPane: typeof import('nutui-uniapp/components/tabpane/tabpane.vue')['default']
    NutTabs: typeof import('nutui-uniapp/components/tabs/tabs.vue')['default']
  }
}
