/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EgtpBanner: typeof import('./src/components/egtp-banner.vue')['default']
    EgtpCard: typeof import('./src/components/egtp-card.vue')['default']
    EgtpLogisticsList: typeof import('./src/components/egtp-logistics-list.vue')['default']
    EgtpProductList: typeof import('./src/components/egtp-product-list.vue')['default']
    EgtpStoreList: typeof import('./src/components/egtp-store-list.vue')['default']
    EgtpSwiper: typeof import('./src/components/egtp-swiper.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutCell: typeof import('nutui-uniapp/components/cell/cell.vue')['default']
    NutCellGroup: typeof import('nutui-uniapp/components/cellgroup/cellgroup.vue')['default']
    NutCheckbox: typeof import('nutui-uniapp/components/checkbox/checkbox.vue')['default']
    NutDivider: typeof import('nutui-uniapp/components/divider/divider.vue')['default']
    NutForm: typeof import('nutui-uniapp/components/form/form.vue')['default']
    NutFormItem: typeof import('nutui-uniapp/components/formitem/formitem.vue')['default']
    NutGrid: typeof import('nutui-uniapp/components/grid/grid.vue')['default']
    NutGridItem: typeof import('nutui-uniapp/components/griditem/griditem.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutInput: typeof import('nutui-uniapp/components/input/input.vue')['default']
    NutMenu: typeof import('nutui-uniapp/components/menu/menu.vue')['default']
    NutMenuItem: typeof import('nutui-uniapp/components/menuitem/menuitem.vue')['default']
    NutRange: typeof import('nutui-uniapp/components/range/range.vue')['default']
    NutSearchbar: typeof import('nutui-uniapp/components/searchbar/searchbar.vue')['default']
    NutSwiper: typeof import('nutui-uniapp/components/swiper/swiper.vue')['default']
    NutSwiperItem: typeof import('nutui-uniapp/components/swiperitem/swiperitem.vue')['default']
    NutTabPane: typeof import('nutui-uniapp/components/tabpane/tabpane.vue')['default']
    NutTabs: typeof import('nutui-uniapp/components/tabs/tabs.vue')['default']
    NutTag: typeof import('nutui-uniapp/components/tag/tag.vue')['default']
    NutTextarea: typeof import('nutui-uniapp/components/textarea/textarea.vue')['default']
    NutUploader: typeof import('nutui-uniapp/components/uploader/uploader.vue')['default']
  }
}
